### ISSUE TITLE
Name change of repo suggestion

### ISSUE THREAD

**Issue by sunnivin** [sarambl/TeXthesis#2]
What about renaming the repository from TeXthesis to something more specific? For instance something like ´´TeX-MetOs-PhD-Paper´´? 

I think it will be clearer what the repo contains then?

**Comment by sarambl** [comment]
Yep, sounds good. What about 'TeX-PhD-thesis-MetOs'? Think paper is just confusing (no one does monographies here anymore I think).

**Comment by sarambl** [comment]
Changed the name :)
