### ISSUE TITLE
Turning repo into template? 

### ISSUE THREAD

**Issue by sunnivin** [sarambl/TeXthesis#3]
What about turning this repo into a [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)? See for instance [this](https://github.com/sunnivin/exercise-code-review) example. 

Users of your template can then generate a repository from your set-up. I think this is a natural workflow if you want to use this TeX-repo as a starting point for writing your thesis.

**Comment by sarambl** [comment]
I changed it. Donno if I need to do anything else?

**Comment by sunnivin** [comment]
No, that's just what I meant. (Maybe a little overkill to ask for this in an issue, but I thought we also could use this repo as an example of a workflow). 

I will update the MetOs-UiO repo!
